#!/usr/bin/env python3
# v1 2026-05-04 @rew62
"""Generate world land-dot positions for conky terminator map.
Reads worldLow.js (amCharts GeoJSON), rasterizes land polygons,
samples at DOT_STEP degree intervals, writes dots.lua.
"""

import re
import json
from PIL import Image, ImageDraw

# Resolution of the raster land mask (degrees per pixel = 360/RASTER_W)
RASTER_W = 1440
RASTER_H = 720

# Spacing between sample dots (degrees)
DOT_STEP = 1.5

JS_FILE  = "worldLow.js"
OUT_FILE = "dots.lua"

# ---------------------------------------------------------------------------
# Load GeoJSON from amCharts JS wrapper
# ---------------------------------------------------------------------------
with open(JS_FILE) as f:
    js = f.read()

m = re.search(r'const map = (\{.*\})\s*;\s*return map', js, re.DOTALL)
if not m:
    raise RuntimeError("Could not find GeoJSON in " + JS_FILE)

geojson = json.loads(m.group(1))
print(f"Loaded {len(geojson['features'])} features")

# ---------------------------------------------------------------------------
# Rasterize polygons with PIL
# ---------------------------------------------------------------------------
img  = Image.new('L', (RASTER_W, RASTER_H), 0)
draw = ImageDraw.Draw(img)

def coord_to_px(lon, lat):
    x = (lon + 180.0) / 360.0 * RASTER_W
    y = (90.0 - lat)  / 180.0 * RASTER_H
    return (x, y)

def split_antimeridian(ring):
    """Split a coordinate ring into sub-rings wherever it crosses ±180°.
    Returns a list of rings, each safe to rasterize without wrap artifacts."""
    segments = [[]]
    for i, (lon, lat) in enumerate(ring):
        segments[-1].append((lon, lat))
        if i < len(ring) - 1:
            nlon = ring[i + 1][0]
            if abs(nlon - lon) > 180:
                # Interpolate crossing latitude
                t    = (180.0 - abs(lon)) / (abs(nlon - lon))
                clat = lat + t * (ring[i + 1][1] - lat)
                edge_lon = 180.0 if lon > 0 else -180.0
                segments[-1].append((edge_lon, clat))
                segments.append([(-edge_lon, clat)])
    # Merge last segment back into first if the ring didn't actually split
    if len(segments) > 1:
        segments[0] = segments[-1] + segments[0]
        segments = segments[:-1]
    return segments

def rasterize_ring(ring):
    for sub in split_antimeridian(ring):
        pts = [coord_to_px(c[0], c[1]) for c in sub]
        if len(pts) >= 3:
            draw.polygon(pts, fill=255)

for feat in geojson['features']:
    geom = feat['geometry']
    gtype = geom['type']
    if gtype == 'Polygon':
        rasterize_ring(geom['coordinates'][0])
    elif gtype == 'MultiPolygon':
        for poly in geom['coordinates']:
            rasterize_ring(poly[0])

print(f"Rasterized at {RASTER_W}x{RASTER_H}")

# ---------------------------------------------------------------------------
# Sample land dots at DOT_STEP intervals
# ---------------------------------------------------------------------------
pixels = img.load()

dots = []
lat = 90.0 - DOT_STEP / 2.0
while lat > -90.0:
    lon = -180.0 + DOT_STEP / 2.0
    while lon < 180.0:
        px = int((lon + 180.0) / 360.0 * RASTER_W)
        py = int((90.0 - lat)  / 180.0 * RASTER_H)
        px = max(0, min(RASTER_W - 1, px))
        py = max(0, min(RASTER_H - 1, py))
        if pixels[px, py] > 128:
            dots.append((round(lat, 3), round(lon, 3)))
        lon += DOT_STEP
    lat -= DOT_STEP

print(f"Land dots sampled: {len(dots)}")

# ---------------------------------------------------------------------------
# Write dots.lua
# ---------------------------------------------------------------------------
with open(OUT_FILE, 'w') as f:
    f.write("-- World land dot positions: {lat, lon}\n")
    f.write(f"-- Generated by gen_dots.py  step={DOT_STEP}°  count={len(dots)}\n")
    f.write("WORLD_DOTS = {\n")
    for lat, lon in dots:
        f.write(f"  {{{lat},{lon}}},\n")
    f.write("}\n")

print(f"Wrote {OUT_FILE}  ({len(dots)} dots)")
